"""Utility for building the Next.js frontend and writing the AstrBot redirect page.

Directory layout after build:
  pages/moirai/            ← AstrBot Plugin Pages root (served in iframe)
    index.html             ← redirect stub generated by write_redirect_page()
    _app/                  ← React SPA (served by WebuiServer on its own port)
      index.html
      _next/
      ...
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent.parent
_FRONTEND_DIR = _REPO_ROOT / "web" / "frontend"
_OUT_DIR = _FRONTEND_DIR / "out"

# React SPA lives in _app/ so it doesn't conflict with the AstrBot redirect index.html
_PAGES_DIR = _REPO_ROOT / "pages" / "moirai" / "_app"
_PAGES_INDEX = _PAGES_DIR / "index.html"

_CONDA_NODE_BIN = Path.home() / "miniconda3" / "envs" / "node" / "bin"

_REDIRECT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Moirai Memory Engine</title>
  <style>
    *{{box-sizing:border-box;margin:0;padding:0}}
    body{{font-family:system-ui,-apple-system,sans-serif;display:flex;
         align-items:center;justify-content:center;min-height:100vh;
         background:#f8f8f8;color:#222}}
    .card{{text-align:center;padding:2.5rem 2rem;max-width:380px;
         background:#fff;border-radius:1rem;box-shadow:0 10px 25px -5px rgba(0,0,0,0.1)}}
    h1{{font-size:1.6rem;font-weight:700;letter-spacing:-.02em;margin-bottom:.4rem;color:#111}}
    .sub{{font-size:.75rem;letter-spacing:.12em;text-transform:uppercase;
          color:#6366f1;margin-bottom:1.6rem;font-weight:600}}
    p{{color:#555;font-size:.9rem;line-height:1.6;margin-bottom:1.8rem}}
    a.btn{{display:inline-block;padding:.8rem 2.2rem;background:#6366f1;
           color:#fff;border-radius:.6rem;text-decoration:none;
           font-size:.95rem;font-weight:500;transition:all .15s ease}}
    a.btn:hover{{background:#4f46e5;transform:translateY(-1px);box-shadow:0 4px 12px rgba(99,102,241,0.3)}}
    a.btn:active{{transform:translateY(0)}}
    .note{{margin-top:1.5rem;padding-top:1.2rem;border-top:1px solid #eee;
           font-size:.78rem;color:#999;word-break:break-all}}
    code{{background:#f1f5f9;padding:.2rem .4rem;border-radius:.3rem;
          color:#475569;font-family:monospace;margin-top:.4rem;display:inline-block}}
  </style>
</head>
<body>
  <div class="card">
    <h1>Moirai</h1>
    <div class="sub">Memory Engine</div>
    <p>WebUI 运行在独立服务器上。<br>点击下方按钮在新标签页中打开。</p>
    <a class="btn" href="#" id="link" target="_blank" rel="noopener">打开 WebUI</a>
    <div class="note">
      无法点击？请手动访问：<br>
      <code id="url-display">http://<host>:{port}</code>
    </div>
  </div>
  <script>
    (function() {{
      var port = {port};
      var host = window.location.hostname || '127.0.0.1';
      
      // Handle sandbox null origin or empty hostname
      if (host === 'null' || host === '') {{
        host = window.location.host.split(':')[0] || '127.0.0.1';
      }}
      
      // IPv6 wrapping
      if (host.indexOf(':') > -1 && host.indexOf('[') === -1) {{
        host = '[' + host + ']';
      }}
      
      var url = 'http://' + host + ':' + port;
      var el = document.getElementById('link');
      var display = document.getElementById('url-display');
      
      el.href = url;
      if (display) display.textContent = url;
      
      // AstrBot sandbox may block target="_blank"; use window.open with fallback
      el.onclick = function(e) {{
        e.preventDefault();
        var opened = window.open(url, '_blank', 'noopener,noreferrer');
        if (!opened) {{
          try {{ window.top.location.href = url; }}
          catch(ex) {{ window.location.href = url; }}
        }}
      }};
    }})();
  </script>
</body>
</html>
"""


def _find_npm() -> str | None:
    if shutil.which("npm"):
        return "npm"
    candidate = _CONDA_NODE_BIN / "npm"
    if candidate.exists():
        return str(candidate)
    return None


def write_redirect_page(port: int) -> None:
    """Write pages/moirai/index.html — a lightweight redirect stub for AstrBot Plugin Pages.

    This page is served by AstrBot in a sandboxed iframe. It contains no external
    assets (inline CSS/JS only) and redirects users to the standalone WebuiServer.
    Called at plugin startup so the port is always up-to-date.
    """
    redirect_path = _REPO_ROOT / "pages" / "moirai" / "index.html"
    redirect_path.parent.mkdir(parents=True, exist_ok=True)
    redirect_path.write_text(_REDIRECT_TEMPLATE.format(port=port), encoding="utf-8")
    logger.debug("[FrontendBuild] Redirect page written → %s (port %d)", redirect_path, port)


def build_frontend(force: bool = False) -> bool:
    """Build the Next.js frontend and sync output to pages/moirai/_app/.

    Skips the build if pages/moirai/_app/index.html already exists and force=False.
    Returns True on success, False on failure.
    """
    if not force and _PAGES_INDEX.exists():
        logger.debug("[FrontendBuild] pages/moirai/_app/ already built, skipping.")
        return True

    if not _FRONTEND_DIR.exists():
        logger.error("[FrontendBuild] Frontend source not found at %s", _FRONTEND_DIR)
        return False

    npm = _find_npm()
    if npm is None:
        logger.error(
            "[FrontendBuild] npm not found. "
            "Install Node.js or activate the 'node' conda env and retry."
        )
        return False

    env = os.environ.copy()
    if str(_CONDA_NODE_BIN) not in env.get("PATH", ""):
        env["PATH"] = str(_CONDA_NODE_BIN) + os.pathsep + env.get("PATH", "")

    logger.info("[FrontendBuild] Building frontend (npm run build) …")
    try:
        result = subprocess.run(
            [npm, "run", "build"],
            cwd=_FRONTEND_DIR,
            env=env,
            capture_output=True,
            text=True,
        )
    except Exception as exc:
        logger.error("[FrontendBuild] npm run build failed to start: %s", exc)
        return False

    if result.returncode != 0:
        logger.error(
            "[FrontendBuild] npm run build failed (exit %d):\n%s\n%s",
            result.returncode,
            result.stdout[-2000:],
            result.stderr[-2000:],
        )
        return False

    if not _OUT_DIR.exists():
        logger.error("[FrontendBuild] Build finished but out/ not found.")
        return False

    if _PAGES_DIR.exists():
        shutil.rmtree(_PAGES_DIR)
    shutil.copytree(_OUT_DIR, _PAGES_DIR)

    logger.info("[FrontendBuild] Frontend built successfully → %s", _PAGES_DIR)
    return True
