"""Utility for building the Next.js frontend and writing the AstrBot redirect page.

Directory layout after build:
  pages/moirai/            ← AstrBot Plugin Pages root (served in iframe)
    index.html             ← redirect stub generated by write_redirect_page()
    _app/                  ← React SPA (served by WebuiServer on its own port)
      index.html
      _next/
      ...
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent.parent
_FRONTEND_DIR = _REPO_ROOT / "web" / "frontend"
_OUT_DIR = _FRONTEND_DIR / "out"

# React SPA lives in _app/ so it doesn't conflict with the AstrBot redirect index.html
_PAGES_DIR = _REPO_ROOT / "pages" / "moirai" / "_app"
_PAGES_INDEX = _PAGES_DIR / "index.html"

_CONDA_NODE_BIN = Path.home() / "miniconda3" / "envs" / "node" / "bin"

_REDIRECT_TEMPLATE = """\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Moirai Memory Engine</title>
  <style>
    *{{box-sizing:border-box;margin:0;padding:0}}
    body{{font-family:system-ui,-apple-system,sans-serif;display:flex;
         align-items:center;justify-content:center;min-height:100vh;
         background:#f8f8f8;color:#222}}
    .card{{text-align:center;padding:2.5rem 2rem;max-width:380px}}
    h1{{font-size:1.6rem;font-weight:700;letter-spacing:-.02em;margin-bottom:.4rem}}
    .sub{{font-size:.75rem;letter-spacing:.12em;text-transform:uppercase;
          color:#888;margin-bottom:1.6rem}}
    p{{color:#555;font-size:.9rem;line-height:1.6;margin-bottom:1.8rem}}
    a.btn{{display:inline-block;padding:.7rem 2rem;background:#6366f1;
           color:#fff;border-radius:.5rem;text-decoration:none;
           font-size:.95rem;transition:background .15s}}
    a.btn:hover{{background:#4f46e5}}
    .note{{margin-top:1.2rem;font-size:.78rem;color:#aaa}}
  </style>
</head>
<body>
  <div class="card">
    <h1>Moirai</h1>
    <div class="sub">Memory Engine</div>
    <p>WebUI 运行在独立服务器上。<br>点击下方按钮在新标签页中打开。</p>
    <a class="btn" href="#" id="link" target="_blank" rel="noopener">打开 WebUI</a>
    <p class="note">默认地址：<code>http://&lt;host&gt;:{port}</code></p>
  </div>
  <script>
    var port = {port};
    var el = document.getElementById('link');
    el.href = 'http://' + location.hostname + ':' + port;
  </script>
</body>
</html>
"""


def _find_npm() -> str | None:
    if shutil.which("npm"):
        return "npm"
    candidate = _CONDA_NODE_BIN / "npm"
    if candidate.exists():
        return str(candidate)
    return None


def write_redirect_page(port: int) -> None:
    """Write pages/moirai/index.html — a lightweight redirect stub for AstrBot Plugin Pages.

    This page is served by AstrBot in a sandboxed iframe. It contains no external
    assets (inline CSS/JS only) and redirects users to the standalone WebuiServer.
    Called at plugin startup so the port is always up-to-date.
    """
    redirect_path = _REPO_ROOT / "pages" / "moirai" / "index.html"
    redirect_path.parent.mkdir(parents=True, exist_ok=True)
    redirect_path.write_text(_REDIRECT_TEMPLATE.format(port=port), encoding="utf-8")
    logger.debug("[FrontendBuild] Redirect page written → %s (port %d)", redirect_path, port)


def build_frontend(force: bool = False) -> bool:
    """Build the Next.js frontend and sync output to pages/moirai/_app/.

    Skips the build if pages/moirai/_app/index.html already exists and force=False.
    Returns True on success, False on failure.
    """
    if not force and _PAGES_INDEX.exists():
        logger.debug("[FrontendBuild] pages/moirai/_app/ already built, skipping.")
        return True

    if not _FRONTEND_DIR.exists():
        logger.error("[FrontendBuild] Frontend source not found at %s", _FRONTEND_DIR)
        return False

    npm = _find_npm()
    if npm is None:
        logger.error(
            "[FrontendBuild] npm not found. "
            "Install Node.js or activate the 'node' conda env and retry."
        )
        return False

    env = os.environ.copy()
    if str(_CONDA_NODE_BIN) not in env.get("PATH", ""):
        env["PATH"] = str(_CONDA_NODE_BIN) + os.pathsep + env.get("PATH", "")

    logger.info("[FrontendBuild] Building frontend (npm run build) …")
    try:
        result = subprocess.run(
            [npm, "run", "build"],
            cwd=_FRONTEND_DIR,
            env=env,
            capture_output=True,
            text=True,
        )
    except Exception as exc:
        logger.error("[FrontendBuild] npm run build failed to start: %s", exc)
        return False

    if result.returncode != 0:
        logger.error(
            "[FrontendBuild] npm run build failed (exit %d):\n%s\n%s",
            result.returncode,
            result.stdout[-2000:],
            result.stderr[-2000:],
        )
        return False

    if not _OUT_DIR.exists():
        logger.error("[FrontendBuild] Build finished but out/ not found.")
        return False

    if _PAGES_DIR.exists():
        shutil.rmtree(_PAGES_DIR)
    shutil.copytree(_OUT_DIR, _PAGES_DIR)

    logger.info("[FrontendBuild] Frontend built successfully → %s", _PAGES_DIR)
    return True
