-- Normalize ipc_orientation values to canonical English keys.
-- Maps all known Chinese labels and LLM variants to the 8 English keys.
UPDATE impressions
SET ipc_orientation = CASE ipc_orientation
  WHEN '亲和'       THEN 'affinity'
  WHEN '友好'       THEN 'affinity'
  WHEN 'friend'     THEN 'affinity'
  WHEN 'friendly'   THEN 'affinity'
  WHEN 'family'     THEN 'affinity'
  WHEN '活跃'       THEN 'active'
  WHEN '积极'       THEN 'active'
  WHEN '掌控'       THEN 'dominant'
  WHEN '支配'       THEN 'dominant'
  WHEN '掌控友好'   THEN 'dominant'
  WHEN '支配友好'   THEN 'dominant'
  WHEN '高傲'       THEN 'arrogant'
  WHEN '傲慢'       THEN 'arrogant'
  WHEN '冷淡'       THEN 'cold'
  WHEN '疏远'       THEN 'cold'
  WHEN '敌意'       THEN 'cold'
  WHEN 'rival'      THEN 'cold'
  WHEN 'stranger'   THEN 'cold'
  WHEN '孤避'       THEN 'withdrawn'
  WHEN '孤立'       THEN 'withdrawn'
  WHEN '顺应'       THEN 'submissive'
  WHEN '服从'       THEN 'submissive'
  WHEN '顺从'       THEN 'submissive'
  WHEN '谦让'       THEN 'deferential'
  WHEN '谦逊'       THEN 'deferential'
  -- already valid keys pass through unchanged
  WHEN 'affinity'     THEN 'affinity'
  WHEN 'active'       THEN 'active'
  WHEN 'dominant'     THEN 'dominant'
  WHEN 'arrogant'     THEN 'arrogant'
  WHEN 'cold'         THEN 'cold'
  WHEN 'withdrawn'    THEN 'withdrawn'
  WHEN 'submissive'   THEN 'submissive'
  WHEN 'deferential'  THEN 'deferential'
  ELSE 'affinity'
END;
